package youtubeexplode.videos.closedcaptions;

/** Metadata associated with a closed caption track. */
public final class ClosedCaptionTrackInfo {
    private final String url;
    private final Language language;
    private final boolean isAutoGenerated;

    public ClosedCaptionTrackInfo(String url, Language language, boolean isAutoGenerated) {
        this.url = url;
        this.language = language;
        this.isAutoGenerated = isAutoGenerated;
    }

    public String getUrl() {
        return url;
    }

    public Language getLanguage() {
        return language;
    }

    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    @Override
    public String toString() {
        return "CC Track (" + language + ")";
    }
}
