package youtubeexplode.videos.closedcaptions;

import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.function.DoubleConsumer;
import youtubeexplode.YoutubeHttp;
import youtubeexplode.bridge.ClosedCaptionTrackResponse;
import youtubeexplode.bridge.PlayerResponse;
import youtubeexplode.exceptions.YoutubeExplodeException;
import youtubeexplode.videos.VideoId;

/** Operations related to closed captions of YouTube videos. */
public final class ClosedCaptionClient {
    private final ClosedCaptionController controller;

    public ClosedCaptionClient(YoutubeHttp http) {
        this.controller = new ClosedCaptionController(http);
    }

    /** Gets the manifest that lists available closed caption tracks for the specified video. */
    public ClosedCaptionManifest getManifest(VideoId videoId) {
        PlayerResponse playerResponse = controller.getPlayerResponse(videoId);

        List<ClosedCaptionTrackInfo> tracks = new ArrayList<>();
        for (PlayerResponse.ClosedCaptionTrackData trackData : playerResponse.closedCaptionTracks()) {
            if (trackData.url() == null) throw new YoutubeExplodeException("Failed to extract the track URL.");
            if (trackData.languageCode() == null) {
                throw new YoutubeExplodeException("Failed to extract the track language code.");
            }
            if (trackData.languageName() == null) {
                throw new YoutubeExplodeException("Failed to extract the track language name.");
            }

            tracks.add(new ClosedCaptionTrackInfo(
                    trackData.url(),
                    new Language(trackData.languageCode(), trackData.languageName()),
                    trackData.isAutoGenerated()));
        }

        return new ClosedCaptionManifest(tracks);
    }

    public ClosedCaptionManifest getManifest(String videoIdOrUrl) {
        return getManifest(VideoId.parse(videoIdOrUrl));
    }

    /** Gets the closed caption track identified by the specified metadata. */
    public ClosedCaptionTrack get(ClosedCaptionTrackInfo trackInfo) {
        ClosedCaptionTrackResponse response = controller.getClosedCaptionTrackResponse(trackInfo.getUrl());

        List<ClosedCaption> captions = new ArrayList<>();
        for (ClosedCaptionTrackResponse.CaptionData captionData : response.captions()) {
            String text = captionData.text();

            // Skip over empty captions, but not captions containing only whitespace
            // https://github.com/Tyrrrz/YoutubeExplode/issues/671
            if (text == null || text.isEmpty()) continue;

            // Auto-generated captions may be missing offset or duration
            // https://github.com/Tyrrrz/YoutubeExplode/discussions/619
            Duration offset = captionData.offset();
            Duration duration = captionData.duration();
            if (offset == null || duration == null) continue;

            List<ClosedCaptionPart> parts = new ArrayList<>();
            for (ClosedCaptionTrackResponse.PartData partData : captionData.parts()) {
                String partText = partData.text();

                // Skip over empty parts, but not parts containing only whitespace
                // https://github.com/Tyrrrz/YoutubeExplode/issues/671
                if (partText == null || partText.isEmpty()) continue;

                parts.add(new ClosedCaptionPart(partText, partData.offset()));
            }

            captions.add(new ClosedCaption(text, offset, duration, parts));
        }

        return new ClosedCaptionTrack(captions);
    }

    private static String formatTimestamp(Duration value) {
        return "%02d:%02d:%02d,%03d"
                .formatted(value.toHours(), value.toMinutesPart(), value.toSecondsPart(), value.toMillisPart());
    }

    /** Writes the closed caption track to the writer in the SRT format. */
    public void writeTo(ClosedCaptionTrackInfo trackInfo, Writer writer, DoubleConsumer progress) throws IOException {
        // Would be better to stream captions as they are parsed, but we need the
        // total number of captions to report progress.
        ClosedCaptionTrack track = get(trackInfo);

        List<ClosedCaption> captions = track.getCaptions();
        for (int i = 0; i < captions.size(); i++) {
            if (Thread.currentThread().isInterrupted()) {
                throw new java.io.InterruptedIOException("Writing captions was interrupted.");
            }

            ClosedCaption caption = captions.get(i);

            // Caption text may contain valid SRT-formatted data in itself.
            // SRT file format does not provide any means of escaping special
            // characters, so as a workaround we just replace the dashes in the
            // arrow sequence with en-dashes, which look similar enough.
            // https://github.com/Tyrrrz/YoutubeExplode/issues/755
            String text = caption.getText().replace("-->", "––>");

            writer.write((i + 1) + System.lineSeparator()
                    + formatTimestamp(caption.getOffset())
                    + " --> "
                    + formatTimestamp(caption.getOffset().plus(caption.getDuration()))
                    + System.lineSeparator()
                    + text
                    + System.lineSeparator()
                    + System.lineSeparator());

            if (progress != null) progress.accept((i + 1.0) / captions.size());
        }
    }

    public void writeTo(ClosedCaptionTrackInfo trackInfo, Writer writer) throws IOException {
        writeTo(trackInfo, writer, null);
    }

    /** Downloads the closed caption track to the specified file in the SRT format. */
    public void download(ClosedCaptionTrackInfo trackInfo, Path filePath, DoubleConsumer progress) throws IOException {
        try (Writer writer = Files.newBufferedWriter(filePath, StandardCharsets.UTF_8)) {
            writeTo(trackInfo, writer, progress);
        }
    }

    public void download(ClosedCaptionTrackInfo trackInfo, Path filePath) throws IOException {
        download(trackInfo, filePath, null);
    }
}
